# Generated by Django 4.0 on 2022-02-11 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_feedback_message_alter_feedback_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback',
            new_name='Contact',
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Contact'},
        ),
    ]
